services:
  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - appnet

  app:
    container_name: app
    hostname: app
    build:
      context: .
      dockerfile: app/Dockerfile
    restart: on-failure
    env_file:
      - .env
    ports:
      - "8900:8000"
    networks:
      - appnet


networks:
  appnet:
    name: app
    driver: bridge
