[tool.poetry]
name = "bonus_accrual_test_task"
version = "0.1.0"
authors = ["FOURWORDSALLCAPS"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "3.13.1"
fastapi = { extras = ["all"], version = "0.115.2" }
uvicorn = { extras = ["standard"], version = "0.34.0" }
